utn_usuario:
    resource: "@UTNUsuarioBundle/Resources/config/routing.yml"
    prefix:   /

utn_dashboard_main:
    resource: "@UTNDashboardMainBundle/Resources/config/routing.yml"
    prefix:   /

# app/config/routing.yml
app:
    resource: "@AppBundle/Controller/"
    type:     annotation

admin_area:
    resource: "@SonataAdminBundle/Resources/config/routing/sonata_admin.xml"
    prefix: /admin